### PR TITLE
wrapping to have two parameters

### PR DESCRIPTION
**Pull request by Celthi**

### CODE REVIEW

**Review by yanqi27 — APPROVED** [review]
LGTM
I am thinking to reduce the duplicate code but still be easy to add support for new allocator version.

**Comment by Celthi** [comment]
> LGTM I am thinking to reduce the duplicate code but still be easy to add support for new allocator version.

@myan Yeah. It would be great that there are fewer duplicate codes as duplicate code is kind of hard to manage. 
Given that there are many duplicate codes for pt allocator. I was thinking of some progressive way: refactoring out one function at a time. 
After some thoughts, one approach is to encapsulate all the existing functions of the pt allocators into a name space, and replacing one function at each step.

I have a sample at https://github.com/yanqi27/core_analyzer/compare/master...Celthi:ubuntu2204?expand=1, but I got distracted and the PR is not ready.

**Comment by Celthi** [comment]
@yanqi27 I will not replace most of the `read_memory_wrapper` as the number of them is large. I think we can merge this PR and replace them along the process we removing the duplicate codes as removing duplicate codes is more important than this cosmetic enhancement. We have a talk about how to remove the duplicate code in a progressive approach in which we can make small progress at each time and reach the final goal in the future.

**Comment by Celthi** [comment]
An overview of the steps of the progressive approach I present in my previous comment:
1. Create namespace `pt_malloc_common` in a file.
2. Add the `get_glibc_version` function into the above namespace `pt_malloc_common`
3. In other heap_pt_malloc_2.x.cpp file, call the `pt_malloc_common::get_glibc_version`.
4. Repeat step 2 and 3 for another function until there are no common functions left.

**Pull request merged**
